' ******************************************************************************
' swxJRNL.swj - journal recorded on 08/24/22 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "shoulderAssembly.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.2886338250485628865, 1.120303795336740071, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0366112351417235346, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05125572919841294567, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04393348217006824014, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.06590022325510236367, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04393348217006824014, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0073222470283447064, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0146444940566894128, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.05125572919841294567, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.0585779762267576512, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.08054471731179177474, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01030835089459153364, -0.08054471731179177474, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.07322247028344706921, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003436116964863844114, -0.05125572919841294567, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0951892113684811858, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01374446785945537645, -0.2050229167936517827, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05497787143782150582, -0.278245387077098838, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02061670178918306728, -0.3075343751904776601, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.1025114583968258913, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.139122693538549419, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.06590022325510236367, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.0585779762267576512, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02748893571891075291, -0.1025114583968258913, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, -0.06590022325510236367, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.0585779762267576512, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03436116964863843853, -0.04393348217006824014, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04466952054322997218, -0.0951892113684811858, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02405281875404690836, -0.0585779762267576512, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006872233929727688227, -0.0073222470283447064, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01374446785945537645, -0.0292889881133788256, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.04393348217006824014, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04466952054322997218, -0.07322247028344706921, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04466952054322997218, -0.1098337054251706107, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04810563750809381672, -0.08786696434013648027, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03779728661350228308, -0.05125572919841294567, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02061670178918306728, -0.04393348217006824014, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01718058482431921927, -0.04393348217006824014, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0146444940566894128, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0146444940566894128, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006872233929727688227, -0.02196674108503412007, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02748893571891075291, -0.0146444940566894128, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05841398840268535037, -0.04393348217006824014, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07903069019186842459, -0.06590022325510236367, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03436116964863843853, -0.02196674108503412007, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02405281875404690836, -0.0146444940566894128, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003436116964863844114, -0.0073222470283447064, 0.0375112078377526359, 0.08128030547879916412, 1.089234481087885342

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Close Document
swAssembly = Nothing
Set Part = Nothing
swApp.CloseDoc "shoulderAssembly.SLDASM"
swApp.ExitApp
End Sub
